collections:
  - name: community.general
    source: https://aap.apps.hub.aws.tntinfra.net/api/galaxy/content/community/

  - name: ansible.windows
    source: https://aap.apps.hub.aws.tntinfra.net/api/galaxy/content/rh-certified/